name: conpassione/dogtraining
typeName: dogtraining
group: z-cpextensions
prefixFields: false
fields:
  - identifier: conpassione/Header
    type: Basic
  - identifier: feuser
    type: Select
    renderType: selectSingle
    foreign_table: fe_users
    foreign_table_where: 'AND {#fe_users}.{#status}>0'
    labelField: last_name,first_name,email2
  - identifier: bodytext
    type: Textarea
    rows: 6
    enableRichtext: true
  - identifier: schedule
    type: Textarea
    rows: 6
    enableRichtext: true
