identifier: membership-application-kvm
label: Mitgliedschaftsantragsformular KVM
type: Form
prototypeName: standard
renderingOptions:
  submitButtonLabel: Absenden
finishers:
  - identifier: EmailToSender
    options:
      subject: 'Bestätigungsmail Mitgliedschaftsantrag'
      recipients:
        '{email}': '{lastname} {firstname}'
      senderAddress: 'info@csbp.ch'
      senderName: 'Club Suisse du Berger des Pyrénées'
      addHtmlPart: true
      attachUploads: false
      title: 'Mitgliedschaftsantrag'
  - identifier: EmailToReceiver
    options:
      subject: 'Mitgliedschaftsantrag von {lastname} {firstname}'
      recipients:
        info@csbp.ch: 'Club Suisse du Berger des Pyrénées'
      senderAddress: '{email}'
      senderName: '{lastname} {firstname}'
      addHtmlPart: true
      attachUploads: false
      title: 'Mitgliedschaftsantrag via Website von {firstname} {lastname}'
  - identifier: Confirmation
    options:
      message: 'Besten Dank für Deine Anmeldung. Wir werden uns innerhalb einer Woche bei Ihnen melden.'
      contentElementUid: ''

renderables:
  - renderingOptions:
      previousButtonLabel: 'Vorherige Seite'
      nextButtonLabel: 'Weiter'
    type: Page
    identifier: page-1
    label: 'Antrag auf Mitgliedschaft KVM'
    renderables:
      - properties:
          options:
            - '---'
            - 'Herr'
            - 'Frau'
          elementDescription: 'Bitte Anrede wählen'
        identifier: salutation
        type: SingleSelect
        label: 'Anrede'
        defaultValue: 0
      - type: GridRow
        identifier: gridrow-1
        label: 'Grid: Zeile'
        renderables:
          - defaultValue: ''
            type: Text
            identifier: lastname
            label: 'Name'
            properties:
              elementDescription: 'Nachname des Mitgliedes'
              fluidAdditionalAttributes:
                required: required
                placeholder: ''
              validationErrorMessages:
                - code: 1238110957
                  message: 'Bitte Name erfassen'
            validators:
              - identifier: NotEmpty
          - defaultValue: ''
            type: Text
            identifier: firstname
            label: 'Vorname'
            properties:
              elementDescription: 'Vorname des Mitgliedes'
              fluidAdditionalAttributes:
                required: required
              validationErrorMessages:
                - code: 1221560910
                  message: 'Bitte Vorname ausfüllen'
            validators:
              - identifier: NotEmpty
      - defaultValue: ''
        type: Textarea
        identifier: address
        label: 'Adresse'
      - type: GridRow
        identifier: gridrow-2
        label: 'Grid: Zeile'
        renderables:
          - defaultValue: ''
            identifier: zipcode
            type: Text
            label: PLZ
          - defaultValue: ''
            identifier: city
            type: Text
            label: Ort
      - type: GridRow
        identifier: gridrow-3
        label: 'Grid: Zeile'
        renderables:
          - defaultValue: ''
            type: Text
            identifier: mobile
            label: Mobiltelefon
            properties:
              elementDescription: ''
          - defaultValue: ''
            type: Text
            identifier: email
            label: E-Mail
            properties:
              fluidAdditionalAttributes:
                required: required
              validationErrorMessages:
                - code: 1221559976
                  message: 'Die E-Mail ist für die Kommunikation nötig, bitte gültige E-Mail erfassen.'
            validators:
              - identifier: EmailAddress
              - identifier: NotEmpty
      - type: Checkbox
        identifier: confirmation
        label: 'Ich bin einverstanden, dass die erfassten Daten für die Zwecke des Club verwendet und im Mitgliederverzeichnis der SKG aufgeführt werden.'
        properties:
          elementDescription: ''
          fluidAdditionalAttributes:
            required: required
          validationErrorMessages:
            - code: 1221560910
              message: 'Bitte Verwendung der Daten zustimmen.'
        validators:
          - identifier: NotEmpty
      - identifier: smrecinfo
        properties:
          text: '* Pflichtfelder'
        type: StaticText
        label: ''
  - renderingOptions:
      previousButtonLabel: 'Vorherige Seite'
      nextButtonLabel: 'Nächster Schritt'
    type: SummaryPage
    identifier: summarypage-1
    label: Zusammenfassung
