# default settings, should be overwritten

TCEpage:
  author: 'KV-Münsingen'
  author_email: info@kv-muensingen.ch
  author_phone: '+41790000000'
  org_name: 'KV-Münsingen'
  org_logo: 'EXT:kvm/Resources/Public/Images/Logo.svg'

